server:
  port: 7071
spring:
  application:
    name: ApplicationRegistrationService
  config:
    import: optional:configserver:http://localhost:8888
ar:
  ssa-web:
   url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
