server:
  port: 7071
spring:
  application:
    name: ApplicationRegistrationService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root123
    url: jdbc:postgresql://localhost:5432/ish-db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
ar:
  ssa-web:
   url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
