server:
  port: 7072
spring:
  application:
    name: DataCollection
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root123
    url: jdbc:postgresql://localhost:5432/ish-db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
