server:
  port: 7072
spring:
  application:
    name: DataCollection
  config:
     import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka