server:
  port: 7073
spring:
  application:
    name: EligiblityDeterminationService
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka