server:
  port: 7073
spring:
  application:
    name: EligiblityDeterminationService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root123
    url: jdbc:postgresql://localhost:5432/ish-db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka