server:
  port : 7076
spring:
  application:
    name: CorrespodenceAPI
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: anilghuge@gmail.com
    password: ahzhwzhndoulhhygx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
