server:
  port : 7075
spring:
  application:
    name: CorrespodenceAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root123
    url: jdbc:postgresql://localhost:5432/ish-db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: anilghuge@gmail.com
    password: ahzhwzhndoulhhygx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
