server:
  port : 7075
spring:
 batch:
   job:
     enabled: false
   jdbc:
     initialize-schema: always
 application:
    name: BenefitIssunaceAPI
 config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
