server:
  port: 8888
spring:
  application:
    name: ConfigServerGit
  cloud:
    config:
      server:
        bootstrap: false
        git:
          clone-on-start: true
          skip-ssl-validation: true
          uri: https://github.com/anilghuge/javarealtimeproject.git
