server:
  port: 7074

spring:
  boot:
    admin:
      client:
        url: http://localhost:9998
  application:
    name: AdminAPI
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
